language: node_js

node_js:
  - "node"

sudo: required

services:
  - docker

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn

stages:
  - name: test
  - name: push to dockerhub
    if: tag IS present

jobs:
  include:
    - stage: test
      script:
        - yarn lint
      name: lint
    - stage: test
      script:
        - yarn install
        - yarn test
      name: integration tests
    - stage: push to dockerhub
      script:
        - docker build -t carlosms/gitbase-graphql:latest -t carlosms/gitbase-graphql:$TRAVIS_BRANCH .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push carlosms/gitbase-graphql:latest
        - docker push carlosms/gitbase-graphql:$TRAVIS_BRANCH
