version: '3.3'

services:
  gitbase-graphql:
    image: "carlosms/gitbase-graphql"
    ports:
      - "3000:3000"
    environment:
      GITBASE_GQL_DB_HOST: gitbase
    depends_on:
      - gitbase
  gitbase:
    image: "srcd/gitbase:v0.16.0"
    ports:
      - "3306:3306"
    environment:
      BBLFSH_ENDPOINT: bblfsh:9432
    volumes:
      - ${GITBASE_GQL_REPOS_FOLDER}:/opt/repos
  bblfsh:
    image: "bblfsh/bblfshd:v2.9.0-drivers"
    privileged: true
    ports:
      - "9432:9432"
